# Generated by Django 2.2.1 on 2019-07-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=25)),
                ('destination', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
